In [20]:
import numpy as np

In [58]:
a = np.array([[1, 2, 3, 3, 1],[6, 8, 11, 10, 7]]) ### Создаем матрицу

In [59]:
a ### результат

array([[ 1,  2,  3,  3,  1],
       [ 6,  8, 11, 10,  7]])

In [60]:
a = np.transpose(a) ###немного невнимательно прочитала задание, пришлось транспонировать)) 

In [61]:
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [62]:
mean_a = np.mean(a, axis = 0) ### Среднее значение по каждому признаку

In [63]:
mean_a  ### результат

array([2. , 8.4])

In [67]:
a_centered = a - mean_a ### В каждой строке массива "а" отнять по среднему значению

In [68]:
a_centered ### результат

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [69]:
a_centered_sp = np.dot(a_centered[:,0],a_centered[:,1]) ### скалярное произведение столбцов

In [70]:
a_centered_sp ### результат

8.0

In [71]:
b = a_centered_sp / ((a.shape[0]) - 1) ### Делим a_centered_sp на N-1, где N - число наблюдений.

In [72]:
b ### результат от деления

2.0

In [73]:
m = np.cov(np.transpose(a))

In [74]:
m ### результат

array([[1. , 2. ],
       [2. , 4.3]])